'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';

interface User {
  ci: string;
    nombre: string;
      rol: string;
        estado: string;
        }

        export default function PortalPage() {
          const router = useRouter();
            const [user, setUser] = useState<User | null>(null);
              const [loading, setLoading] = useState(true);

                useEffect(() => {
                    // Obtener datos del usuario del localStorage
                        const userData = localStorage.getItem('user');
                            const token = localStorage.getItem('token');

                                if (!token || !userData) {
                                      // Redirigir a login si no hay token
                                            router.push('/login');
                                                  return;
                                                      }

                                                          try {
                                                                const parsedUser = JSON.parse(userData);
                                                                      setUser(parsedUser);
                                                                          } catch (error) {
                                                                                console.error('Error parsing user data:', error);
                                                                                      router.push('/login');
                                                                                          }

                                                                                              setLoading(false);
                                                                                                }, [router]);

                                                                                                  const handleLogout = () => {
                                                                                                      localStorage.removeItem('token');
                                                                                                          localStorage.removeItem('user');
                                                                                                              router.push('/login');
                                                                                                                };

                                                                                                                  if (loading) {
                                                                                                                      return (
                                                                                                                            <div className="min-h-screen flex items-center justify-center">
                                                                                                                                    <p>Cargando...</p>
                                                                                                                                          </div>
                                                                                                                                              );
                                                                                                                                                }

                                                                                                                                                  if (!user) {
                                                                                                                                                      return null;
                                                                                                                                                        }

                                                                                                                                                          return (
                                                                                                                                                              <div className="min-h-screen bg-gray-50">
                                                                                                                                                                    {/* Header */}
                                                                                                                                                                          <header className="bg-white shadow">
                                                                                                                                                                                  <div className="max-w-7xl mx-auto px-4 py-6">
                                                                                                                                                                                            <div className="flex justify-between items-center">
                                                                                                                                                                                                        <h1 className="text-3xl font-bold text-gray-900">Portal del Socio</h1>
                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                  onClick={handleLogout}
                                                                                                                                                                                                                                                className="bg-red-600 text-white px-4 py-2 rounded-md hover:bg-red-700 transition-colors"
                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                          Cerrar Sesión
                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                              </header>

                                                                                                                                                                                                                                                                                                                    {/* Main Content */}
                                                                                                                                                                                                                                                                                                                          <main className="max-w-7xl mx-auto px-4 py-8">
                                                                                                                                                                                                                                                                                                                                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                                                                                                                                                                                                                                                                                                                            {/* Tarjeta de Información Personal */}
                                                                                                                                                                                                                                                                                                                                                      <div className="bg-white rounded-lg shadow-md p-6">
                                                                                                                                                                                                                                                                                                                                                                  <h2 className="text-2xl font-bold mb-4 text-gray-800">Información Personal</h2>
                                                                                                                                                                                                                                                                                                                                                                              <div className="space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                            <label className="block text-sm font-medium text-gray-600">Nombre</label>
                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-lg text-gray-900">{user.nombre}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label className="block text-sm font-medium text-gray-600">Cédula de Identidad (CI)</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-lg text-gray-900 font-mono">{user.ci}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Tarjeta de Estado */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="bg-white rounded-lg shadow-md p-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2 className="text-2xl font-bold mb-4 text-gray-800">Estado del Socio</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <label className="block text-sm font-medium text-gray-600">Rol</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-lg text-gray-900">{user.rol}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label className="block text-sm font-medium text-gray-600">Estado</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium bg-green-100 text-green-800">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {user.estado}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Sección de Bienvenida */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="bg-white rounded-lg shadow-md p-6 mt-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="text-2xl font-bold mb-4 text-gray-800">Bienvenido</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-gray-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Hola <span className="font-semibold">{user.nombre}</span>, bienvenido al Portal del Socio de la Cooperativa Vida y Luz. 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Aquí puedes acceder a tu información personal y estado como miembro de la cooperativa.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }